Use openapi-generator gradle plugin
gradle/gradle-enterprise-api-samples pull request #13
Opened 2022-06-23 15:41 UTC by welandaz

2022-06-23 16:55 UTC, guylabs requested changes
Nice! Looking wsy more structured.

2022-06-23 17:37 UTC, welandaz commented on build.gradle.kts
> +    inputSpec.set(apiSpecificationFile.get().absolutePath)
Done

2022-06-23 17:37 UTC, welandaz commented on build.gradle.kts
> +    outputDir.set("${buildDir}/generated/$name")
Done

2022-06-23 17:37 UTC, welandaz commented on build.gradle.kts
> +    ignoreFileOverride.set("$projectDir/.openapi-generator-ignore")
Done

2022-06-23 17:37 UTC, welandaz commented on build.gradle.kts
> +    modelPackage.set("com.gradle.enterprise.api.model")
Done

2022-06-24 14:01 UTC, guylabs approved these changes
All good now 👍

2022-06-27 06:50 UTC, sorin-florea approved these changes

2022-06-27 09:16 UTC, merged